{
    bem
        =
        import
            (fetchTarball
                https://github.com/monadosquito/bem/archive/main.tar.gz
            );
    miso
        =
        import
            (fetchTarball
                 https://github.com/dmjio/miso/archive/1.8.3.tar.gz
            );
    traverse
        =
        import
            (fetchTarball
                https://github.com/monadosquito/traverse/archive/v1.0.0.tar.gz
            );
   unpath
       =
       import
           (fetchTarball
                https://github.com/monadosquito/unpath/archive/v1.0.0.tar.gz
           );
   nixpkgs
       =
       import
           (fetchTarball
                https://github.com/NixOS/nixpkgs/archive/a7ecde854aee5c4c7cd6177f54a99d2c1ff28a31.tar.gz
            );
}
